# Learning Numpy 


---

In [2]:
import numpy as np

### creating arrays from list 

In [6]:
arr_1d = np.array([1,2,3,4,5])
print ("1D array : " , arr_1d)

arr_2d = np.array([[1,2,3] , [4,5,6]])
print ("2D array : " , arr_2d)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [ ]:
py_list = [4,3,2]
print ("Python list multiplication : " , py_list * 3 )

np_array = np.array([4,3,2])
print ("Python array multiplication : " , np_array * 3 ) 


Python list multiplication :  [4, 3, 2, 4, 3, 2, 4, 3, 2]
Python array multiplication :  [12  9  6]


In [3]:
import time 
import numpy as np 
start = time.time()
li = [i *2 for i in range(100000)]
print (" list time consumed : " , time.time() - start)

start = time.time()
np = np.array(100000) * 2 
print ("array time consumed : " , time.time() - start)

 list time consumed :  0.021233558654785156
array time consumed :  0.014811038970947266


### creating an array from scratch 

In [9]:
# import numpy as np

zero = np.zeros((3,3))
print (zero)

one = np.ones((3,3))
print (one)

full = np.full((3,3), 99)
print (full)

rand = np.random.random((3,3))
print (rand)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[99 99 99]
 [99 99 99]
 [99 99 99]]
[[0.93348593 0.12821195 0.42788238]
 [0.57317785 0.94696391 0.71750505]
 [0.77893854 0.72249237 0.09268468]]


### properties 

In [22]:
arr = np.array([1,2,3,4,5,6,7,8])
print (arr.shape)
print (arr.ndim)
print (arr.size)
print (arr.dtype)

conv_2d = arr.reshape((2,4))
print (conv_2d)
print (arr)

flat = conv_2d.flatten()
print (flat)
print (conv_2d)

rav = conv_2d.ravel()
print (rav)
print (conv_2d)

tensor = np.array([[[1,2] ,[3,4]], [[7,8] , [9,10]]])
print (tensor)

trans = tensor.T
print (trans)

(8,)
1
8
int64
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2]
  [ 3  4]]

 [[ 7  8]
  [ 9 10]]]
[[[ 1  7]
  [ 3  9]]

 [[ 2  8]
  [ 4 10]]]
